fit:
    model:
        in_feats: 47
        out_feats: 10
        num_layers: 3
        hidden_feats: 20
        activation: 'selu'
        lr: .0001

    data:
        batch_size: 128
    
    trainer:
        max_epochs: 1000
        # accelerator: 'gpu'
        # devices: 
        #     - 0
        #     - 1